# configure tertiary appliance-node
# greg.procunier@gmail.com
#
# ansible-playbook -i inventory/<env>-inventory.yml -l tertiaryAppliance play.yml
---
- name: configure tertiary appliance-node
  hosts: all
  tasks:
    - name: fetch remote key from primary db
      shell:
        cmd: |
           . /root/.bash_profile
           /usr/local/bin/appliance_console_cli  --fetch-key={{ primaryDb }} --sshlogin=root --sshpassword=smartvm || exit 1
      register: fetch_key
      failed_when: fetch_key.rc > 0
    - name: join region in external database
      shell:
        cmd: |
          . /root/.bash_profile
          appliance_console_cli --hostname {{ primaryDb }} --username root --password={{ dbPassword }} || exit 1
      register: joinDbRegion
      failed_when: joinDbRegion.rc > 0 or 'Failed to configure external database' in joinDbRegion.stdout_lines
